### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Git-Forked** [daniabib/csgo-aimbot#2]
Using cache found in /home/user/.cache/torch/hub/ultralytics_yolov5_master
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
YOLOv5 🚀 2022-10-16 Python-3.10.7 torch-1.12.1+cu102 CPU

Fusing layers... 
Model summary: 367 layers, 46135203 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "/home/user/Games/csgo-aimbot/aim-bot.py", line 109, in <module>
    main()
  File "/home/user/Games/csgo-aimbot/aim-bot.py", line 84, in main
    cv.imshow('CV TEST', results.imgs[0])
AttributeError: 'Detections' object has no attribute 'imgs'. Did you mean: 'ims'?

**Comment by plozzy04** [comment]
i got that too did u figure how to fix it

**Comment by black-bots** [comment]
change img to ims .

> i got that too did u figure how to fix it
